name: Cargo Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: |
          rustup update stable
          rustup default stable
          rustc --version
          cargo --version

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "auburn-workspace"

      - name: Build workspace
        run: cargo build --workspace --verbose

      - name: Build workspace (all features)
        run: cargo build --workspace --verbose --all-features

      - name: Test workspace
        run: cargo test --workspace --verbose

      - name: Test workspace (all features)
        run: cargo test --workspace --verbose --all-features
